name = "DMCP"
uuid = "151c197c-e44d-40dd-a70d-3018a3e25642"
authors = ["Julian Jandeleit <julian.jandeleit@uni-konstanz.de>"]
version = "0.1.0"

[deps]
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
