name = "DMCP"
authors = ["Julian Jandeleit <julian.jandeleit@uni-konstanz.de>"]
version = "0.1.0"

[deps]
ImageProjectiveGeometry = "b9d14576-938f-5430-9d4c-b7d7de1409d6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
