[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "src"
version = "0.1.1"
dependencies = [
"numpy",
"scipy",
"pyvista"
]
requires-python = "==3.9.18"


[tool.hatch.envs.default]
python="3.9"  # <--
